# Generated by Django 5.0.4 on 2024-04-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blogger_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogger_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogger_ssn',
            field=models.CharField(default='', max_length=100),
        ),
    ]
